### ISSUE TITLE
solution for "chance that we receive the starbyte, but not the complete header." Problem

### ISSUE THREAD

**Issue by RafaelKa** [Holger-Will/node-enocean#12]
I've looked at the code and seen following comment https://github.com/Holger-Will/node-enocean/blob/master/index.js#L75-L76
I think you can use my package for TCM310 device https://github.com/RafaelKa/node-serialport-enocean-parser

see 
https://github.com/RafaelKa/node-serialport-enocean-parser/blob/master/ESP3Packet.js 
and
https://github.com/RafaelKa/node-serialport-enocean-parser/blob/master/ESP3Parser.js

**Comment by Holger-Will** [comment]
Looks interresting! I will have to look at it in more detail. Thanks for the hint.
