### ISSUE TITLE
Newbie question:Send on/off switch commands

### ISSUE THREAD

**Issue by mwittig** [Holger-Will/node-enocean#17]
The following is perhaps a bit off-topic: I have hardware switch and which I have registered with node-ocean using the learning mode. Besides this I have a smartplug which I have paired with the hardware switch. Question: Is it possible to send on/off commands from node-enocean (seeing it as a software representation of the hardware switch) to switch the smartplug?

**Comment by Holger-Will** [comment]
you can send on/off commends with node-enocean. What you can not do though, is mimic other hardware addresses. You have to pair the node-enocean "soft"-switch with your smartplug as well.

there is a special module to make it easier to send switch commands:
https://github.com/Holger-Will/node-enocean-button

with node-enocean-button, you give the soft button an id 1-128 which is used aas an offset to the base address of your usb dievice.

**Comment by mwittig** [comment]
Thanks for the swift reply. If understand you correctly, I'll need two handle two devices if I want to present a smart plug, for example, i.e. the smart plug device to get the current switch state of the plug and a software button to actually switch the plug via software. That's a bit cumbersome, but I understand this is a security feature of enocean.

**Comment by Holger-Will** [comment]
sorry havn't seen your comment... you are absolutely right. if you have any other question, or need help, don't hesitate to ask. 
Closing this now. If you feel your answer hasn't been answered, please reopen.
