### ISSUE TITLE
Syntax error when loading 2.0.0

### ISSUE THREAD

**Issue by 6DammK9** [Holger-Will/node-enocean#22]
Node 6.10.0, Raspberry pi, Debian Jessy.
Found ES7 syntax in source files which are not supported in Node below 7.x
Dodged issue by modifying my `package.json`.

It would be great if environment requirement is updated.

**Comment by Holger-Will** [comment]
yes, i will do so. thanks for the hint.

**Comment by Holger-Will** [comment]
updated package.json. If you think this is not fixing your issue, please reopen.
