### ISSUE TITLE
Error : enocean.startLearning is not a function

### ISSUE THREAD

**Issue by nemr** [Holger-Will/node-enocean#23]
I'm trying to use tge startLearning function but its giving me the following error : 

`TypeError: enocean.startLearning is not a function`

this is the code : 

```
var enocean = require("node-enocean")();
enocean.listen("/dev/ttyUSB0");
enocean.startLearning()
enocean.on("learned",function(data){   
    console.log(data)
});
```

**Comment by Holger-Will** [comment]
startLearning should only be used after the ready event got fired. please try it like this and tell me if it works... it works here...

     enocean.on("ready",function(){
	    enocean.timeout=120
    	    enocean.startLearning()
    }  

p.s.: see the memory.js example in the examples folder

**Comment by nemr** [comment]
thanks , the programme is not crashing now :) .

I already set a device on learning mode , but I didn't get the the learning confirmed response 
`var enocean = require("node-enocean")();
enocean.listen("/dev/ttyUSB0");
 enocean.on("ready",function(){
    enocean.timeout=120
    enocean.startLearning()
});  
enocean.on("learned",function(data){   
    console.log(data)
});
`

**Comment by nemr** [comment]
Hi , its working fine now thats .

Just to let u know I had an error before that which was :

```
/home/pi/Desktop/node_modules/node-enocean/index.js:226
		socket.on( "get-last-sensor-value" , async function( id ) {
		                                     ^^^^^

SyntaxError: missing ) after argument list
```

I took out that function form the index file to get it working since I dont need that function at the moment , but it might be something that you would need to consider .

Thanks again for this great npm

**Comment by Holger-Will** [comment]
> I already set a device on learning mode , but I didn't get the the learning confirmed response

the sensor is most likely already learned in please check your knownSensors file...
(default location is ./node_modules/node-enocean/modules/knownSensors.json)

**Comment by Holger-Will** [comment]
the other error you are seeing is handled in issue #22 
you have to update your node.js to the latest version (7.7.1) for this to work, or start your app with the --harmony-async-await flag

**Comment by nemr** [comment]
Hello Will  ,

thanks for resolving my issues that I posted today .


I just have one extra question if you dont mind ?


I'm trying to write a code that will send a switch telegram once a button connected to a raspberry pi is pressed .


However, I can't see how I can use this function (button.A1.click().then(enocean.close)) once the button is pressed because what I understood is that it has to be within the enocean.on("ready") event handler


What I'm aiming to achieve is like this :

var Gpio = require('onoff').Gpio, // Constructor function for Gpio objects.
  input = new Gpio(21, 'in', 'both');


var enocean = require("node-enocean")();
var Button = require("node-enocean-button")
enocean.listen("/dev/ttyUSB0")

    var button = new Button(enocean,1)

input.watch(function(err, value) {
  if (value==0){
              button.A1.click().then(enocean.close)
          console.log("lights on");
  }
      else if (value==1){
              button.A0.click().then(enocean.close)
          console.log("lights off");
  }
});

so if there is a way to achieve this or a way to trigger the ready event please do let me know :)

many thanks

________________________________
